#!/usr/bin/env python
#
# Copyright 2023 Westwood Robotics Corporation
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, GPL version 3.0, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
#

__author__ = "X. Zhang, Westwood Robotics Corporation"
__email__ = "info@westwoodrobotics.io"
__copyright__ = "Copyright 2023 Westwood Robotics"
__date__ = "Sep. 01, 2023"

__version__ = "0.0.1"
__status__ = "beta"


from element import Element
import sys

class CSV2URDF(object):
    """
    """

    def __init__(self, robot_name, csv_path, urdf_path):
        """
        """
        lines = None
        try:
            csv_file = open(csv_path, "r")
            lines = csv_file.readlines()
            csv_file.close()
        except:
            print("Couldn't open file: "+ csv_path)
            return

        # contains all the elements described in the csv file
        self.elements = []

        self.titles = []

        self.name = robot_name

        index = 0
        while True:
            line = lines[index]
            if index == 0:
                # first line contains titles
                self.get_title(line)
            else:
                self.get_data(line)

            if index < len(lines) - 1:
                index = index + 1
            else:
                break

        robot = self.to_urdf()
        # outputs to the console if no path specified
        urdf_file = sys.stdout
        if urdf_path != None:
            urdf_file = open(urdf_path, "w")
        urdf_file.write(robot)
        urdf_file.close()

    def get_title(self, line):
        splitted_line = line.split(",")
        for title in splitted_line:
            self.titles.append(self.clean(title).upper())

    def get_data(self, line):
        splitted_line = line.split(",")
        data_map = dict()

        for title, data in zip(self.titles, splitted_line):
            data_map[title] = self.clean(data)

        self.elements.append(Element(data_map))

    def clean(self, string):
        return string.strip(" ").strip("\n").strip("\t").strip()

    def to_urdf(self):
        robot = ""
        robot += "<?xml version=\"1.0\" ?>\n"
        robot += "<!-- =================================================================================== -->\n"
        robot += "<!-- |    This document was autogenerated by csv to urdf                               | -->\n"
        robot += "<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->\n"
        robot += "<!-- =================================================================================== -->\n"
        robot += "<robot\n"
        robot += "  name=\"" + self.name + "\">\n"

        for element in self.elements:
            robot += element.to_urdf()

        robot += "</robot>"

        return robot
